### ISSUE TITLE
鶏には取り憑かない

### ISSUE THREAD

**Issue by kurehajime** [kurehajime/dajarep#7]
鶏には取り憑かない
↑
ハをワに読み替えたい。

破壊についての和解
↑
ハをワに読み替えたくない。

**Comment by sawadyecma** [comment]
形態素解析した結果、品詞を見て読み替えるかどうか判別できそうですね。

**Comment by kurehajime** [comment]
@sawady0920 

アドバイスありがとうございます！
さっそく対応しました。
